(function() {var implementors = {};
implementors["polyfuse"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"polyfuse/struct.DirEntryType.html\" title=\"struct polyfuse::DirEntryType\">DirEntryType</a>",synthetic:false,types:["polyfuse::dirent::DirEntryType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"polyfuse/struct.CapabilityFlags.html\" title=\"struct polyfuse::CapabilityFlags\">CapabilityFlags</a>",synthetic:false,types:["polyfuse::session::CapabilityFlags"]},];
implementors["polyfuse_sys"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"polyfuse_sys/kernel/enum.fuse_opcode.html\" title=\"enum polyfuse_sys::kernel::fuse_opcode\">fuse_opcode</a>",synthetic:false,types:["polyfuse_sys::kernel::fuse_opcode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"polyfuse_sys/kernel/enum.fuse_notify_code.html\" title=\"enum polyfuse_sys::kernel::fuse_notify_code\">fuse_notify_code</a>",synthetic:false,types:["polyfuse_sys::kernel::fuse_notify_code"]},];
implementors["polyfuse_tokio"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"polyfuse_tokio/struct.Notifier.html\" title=\"struct polyfuse_tokio::Notifier\">Notifier</a>",synthetic:false,types:["polyfuse_tokio::server::Notifier"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()